apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260624-234729-av51xsj0kzef-service
spec:
  selector:
    app: enterprise-system-20260624-234729-av51xsj0kzef
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
